# Generated by Django 5.1.3 on 2024-11-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_student_user_alter_student_id_stud_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='depart',
            new_name='department',
        ),
    ]
