# Generated by Django 5.1.3 on 2024-11-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_stud_id_student_id_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='d',
        ),
    ]
